import type { GuideContent } from "./wildfire-guide";

/**
 * Spanish (formal "usted", common Latin American usage) translation of the /prepare guide.
 * Unofficial: prepared for Firepoint and pending review by native speakers. Official evacuation
 * terms are also shown in English on the page, because alerts are issued in English.
 */
export const GUIDE_ES: GuideContent = {
  ui: {
    metaTitle: "Firepoint | Listos, preparados, ¡ya!",
    metaDescription: "Una guía sobre incendios forestales para Glendale, adaptada del plan ¡Listos! ¡Preparados! ¡Ya! del Departamento de Bomberos del Condado de Los Ángeles.",
    back: "Mapa",
    title: "Guía de incendios",
    brandLabel: "Mapa de Firepoint",
    chaptersLabel: "Capítulos",
    languageLabel: "Idioma",
    chapter: "Capítulo",
    opensNewTab: "(se abre en una pestaña nueva)",
    publicDomain: "dominio público",
    translationNotice: "Traducción no oficial, preparada por Firepoint y pendiente de revisión por hablantes nativos. Si algo no está claro, la versión en inglés y las fuentes oficiales tienen prioridad.",
    readInEnglish: "Leer en inglés",
    officialTerm: "Término oficial en inglés:",
    coverKicker: "Una guía sobre incendios forestales para Glendale",
    coverTitle: ["Listos.", "Preparados.", "¡Ya!"],
    coverDek: "Aquí los incendios forestales se alimentan de maleza seca y los impulsan vientos fuertes y secos, y muy pocos residentes se preparan para evacuar hasta que es demasiado tarde. Esto es lo que los bomberos le piden que haga: antes de la temporada de incendios, cuando hay un incendio cerca y cuando llega el momento de irse. Basado en el plan ¡Listos! ¡Preparados! ¡Ya! del Departamento de Bomberos del Condado de Los Ángeles.",
    emergencyLabel: "Emergencia",
    urgentCall: "¿Está en peligro? Llame al 911.",
    urgentNote: "Firepoint no es un sistema de alertas y no verifica órdenes de evacuación ni su zona.",
    checkZone: "Consulte su zona",
    signUpAlerts: "Inscríbase en Glendale Alerts",
    inside: "Contenido",
    defensibleTitle: "Espacio defendible",
    defensibleLede: "El espacio defendible es la zona de protección entre su casa y el terreno que la rodea. Hace que el fuego avance más despacio y da a los bomberos espacio para interponerse entre su casa y las llamas. Se extiende 200 pies hacia afuera, en tres zonas.",
    ringsLabel: "Espacio defendible: la Zona 1 va de 0 a 30 pies de la casa, la Zona 2 de 30 a 100 pies y la Zona 3 de 100 a 200 pies.",
    ringsCaption: "Tres zonas, 200 pies en total. Su casa está en el centro.",
    feet: "pies",
    quoteEmbers: "Las brasas que lleva el viento durante un incendio forestal encontrarán el punto débil en la protección contra incendios de su casa.",
    quoteLeaveEarly: "Si sale temprano, le dará a su familia la mejor oportunidad de sobrevivir a un incendio forestal.",
    quoteSource: "Plan de Acción ¡Listos! ¡Preparados! ¡Ya! (Ready! Set! Go!)",
    hardenTitle: "Proteja su casa",
    planTitle: "Su plan de acción contra incendios",
    planLede: "Hágalo con todas las personas de su hogar, mucho antes de la temporada de incendios. Practíquelo y colóquelo donde pueda encontrarlo rápido.",
    kitKicker: "Uno por persona",
    kitTitle: "Kit de suministros de emergencia",
    kitLede: "Una mochila funciona bien. Guarde la comida y el agua en un recipiente que pueda subir al carro.",
    sixPsTitle: "Recuerde las seis P",
    sixPsLede: "Si tiene minutos y no horas, tome estas cosas.",
    beforeLeavingTitle: "Si se acerca una evacuación y hay tiempo",
    termsTitle: "Conozca los términos oficiales",
    termsLedeBefore: "Las autoridades usan estas palabras en las alertas, que suelen llegar en inglés. Sígalas de inmediato. Consulte",
    termsLedeAfter: "para su área.",
    termsQuoted: "Términos citados de",
    goTitle: "Cuando empieza un incendio forestal",
    trappedTitle: "Si queda atrapado",
    trappedLede: "Mantenga la calma. Llame al 911 y diga dónde está.",
    returningTitle: "Al regresar a casa",
    sourcesTitle: "Tenga estas páginas a mano",
    sourcesLede: "Firepoint solo explica las recomendaciones. Para órdenes, zonas y condiciones, consulte la fuente.",
    footerAdapted: "Adaptado del Plan de Acción contra Incendios Forestales ¡Listos! ¡Preparados! ¡Ya! (Ready! Set! Go!) del Departamento de Bomberos del Condado de Los Ángeles (revisado el 20 de mayo de 2026). Las fotos son obras del gobierno de EE. UU. de dominio público.",
    footerDisclaimer: "Herramienta comunitaria independiente, no un servicio del gobierno. Solo orientación general: no ofrece alertas en tiempo real, búsqueda de zonas ni avisos de que el peligro ha pasado. En una emergencia, siga a las autoridades locales. Llame al 911 para recibir ayuda inmediata.",
  },
  chapters: [
    { word: "Listos", topic: "Su casa", line: "Despeje el espacio alrededor de su casa y protéjala contra las brasas." },
    { word: "Preparados", topic: "Su familia", line: "Haga un plan, prepare un kit y sepa qué hacer antes de irse." },
    { word: "Ya", topic: "La salida", line: "Salga temprano, conozca los términos oficiales y qué hacer si queda atrapado." },
  ],
  sources: {
    rsg: "Bomberos del Condado de LA · Ready! Set! Go! (inglés)",
    brochure: "Plan de Acción Ready! Set! Go! (PDF en inglés, mayo de 2026)",
    terms: "Cal OES · Términos oficiales de evacuación (inglés)",
    zone: "Bomberos de Glendale · Know Your Zone (Conozca su zona)",
    alerts: "Glendale Alerts (alertas de la ciudad)",
    nws: "Servicio Meteorológico Nacional · Los Ángeles/Oxnard",
    county: "Información de emergencias del Condado de LA",
  },
  zones: [
    {
      name: "Zona 1", reach: "0–30 pies",
      items: [
        "Retire hojas secas, agujas de pino, maleza y escombros del jardín, el techo, las canaletas, las terrazas y las escaleras.",
        "Corte las ramas a 10 pies de cualquier chimenea o tubo de estufa.",
        "Mantenga las plantas bajas, regadas y bien separadas. Nada de setos a menos de 5 pies de la casa.",
        "Lleve la leña y la madera a la Zona 2.",
      ],
    },
    {
      name: "Zona 2", reach: "30–100 pies",
      items: [
        "Corte el pasto anual a 3 pulgadas o menos.",
        "Separe los árboles y arbustos unos de otros, a unas tres veces su altura.",
        "Retire hojas caídas, ramitas, corteza y ramas pequeñas.",
      ],
    },
    {
      name: "Zona 3", reach: "100–200 pies",
      items: [
        "Reduzca la maleza nativa entre un 30 y un 50 por ciento.",
        "Quite el tercio inferior de los arbustos grandes y toda la madera seca.",
        "Pode las ramas bajas de los árboles hasta al menos 6 pies de altura.",
      ],
    },
  ],
  home: [
    { part: "Techo", tip: "La parte más vulnerable de una casa. Use tejas de composición, metal o teja de barro, manténgalo libre de agujas y hojas, y corte las ramas a 10 pies." },
    { part: "Respiraderos", tip: "Cúbralos con malla metálica de 1/8 de pulgada. La malla de fibra de vidrio o de plástico se derrite." },
    { part: "Ventanas", tip: "El calor puede romper las ventanas antes de que la casa se encienda. Las de doble panel con vidrio exterior templado resisten mejor." },
    { part: "Aleros y canaletas", tip: "Cierre los aleros con material no combustible. Cubra o cierre las canaletas." },
    { part: "Terraza", tip: "Manténgala libre de muebles y de todo lo que pueda arder. Cierre la parte de abajo." },
    { part: "Chimenea", tip: "Cubra las salidas con malla no inflamable de 1/8 de pulgada." },
    { part: "Garaje", tip: "Tenga un extintor, una pala, un rastrillo y una cubeta. Mantenga la puerta cerrada." },
    { part: "Dirección", tip: "Números de al menos 4 pulgadas de alto, de un color que contraste, visibles desde la calle." },
    { part: "Agua", tip: "Mangueras lo bastante largas para llegar a todos los lados de la casa." },
    { part: "Servicios", tip: "Todos en el hogar deben saber cómo cerrar el gas, la electricidad y el agua." },
  ],
  plan: [
    { q: "A quién llamar", a: "Elija a un amigo o familiar que viva fuera del área, con quien todos se reporten. Ponga los números de emergencia junto al teléfono y en su kit." },
    { q: "Dónde reunirse", a: "Elija un lugar de reunión fuera de la zona del incendio, para saber quién logró salir." },
    { q: "Cómo llegar", a: "Conozca varias rutas para salir de su vecindario y practíquelas." },
    { q: "Qué llevar", a: "Un kit de suministros de emergencia por persona y un kit de repuesto en el carro." },
    { q: "Sus animales", a: "Prepare los suministros de sus mascotas. Planee cómo transportar a los animales grandes y muévalos temprano." },
  ],
  kit: [
    "Comida no perecedera para tres días y tres galones de agua por persona",
    "Un mapa con al menos dos rutas de evacuación marcadas",
    "Recetas o medicamentos especiales",
    "Una muda de ropa y zapatos cerrados",
    "Anteojos o lentes de contacto de repuesto",
    "Llaves extra del carro, tarjetas de crédito y dinero en efectivo",
    "Botiquín de primeros auxilios",
    "Linterna",
    "Radio de baterías y baterías extra",
    "Artículos de higiene",
    "Copias de documentos importantes",
    "Comida y agua para sus mascotas",
  ],
  sixPs: [
    { p: "People · Personas", detail: "y mascotas" },
    { p: "Papers · Papeles", detail: "números de teléfono y documentos importantes" },
    { p: "Prescriptions · Recetas", detail: "vitaminas y anteojos" },
    { p: "Pictures · Fotos", detail: "y recuerdos irreemplazables" },
    { p: "Personal computer · Computadora", detail: "discos duros y memorias USB" },
    { p: "Plastic · Tarjetas", detail: "tarjetas de crédito y de débito, y efectivo" },
  ],
  beforeLeaving: [
    { title: "Animales", items: ["Busque a sus mascotas y manténgalas cerca.", "Prepare a los animales grandes para moverlos, y muévalos temprano."] },
    {
      title: "Adentro",
      items: [
        "Cierre todas las ventanas y puertas.",
        "Quite las cortinas y persianas inflamables. Cierre las contraventanas de metal.",
        "Mueva los muebles al centro de las habitaciones, lejos de las ventanas.",
        "Deje las luces encendidas para que los bomberos vean la casa entre el humo.",
        "Apague el aire acondicionado.",
      ],
    },
    {
      title: "Afuera",
      items: [
        "Meta los muebles del patio, los juguetes y los tapetes.",
        "Cierre los tanques de propano. Aleje las parrillas de la casa.",
        "Conecte las mangueras del jardín para los bomberos, pero deje los aspersores apagados. Bajan la presión del agua.",
        "Ponga su kit en el carro. Estaciónelo de reversa en la entrada, con las ventanas cerradas y las llaves con usted.",
        "Verifique cómo están sus vecinos.",
      ],
    },
  ],
  terms: [
    { term: "Advertencia de evacuación", meaning: "Posible amenaza para la vida o la propiedad. Quienes necesitan más tiempo para evacuar, y quienes tienen mascotas o ganado, deben salir ahora." },
    { term: "Orden de evacuación", meaning: "Amenaza inmediata para la vida. Es una orden legal de salir ahora. El área queda legalmente cerrada al acceso público." },
    { term: "Refugiarse en el lugar", meaning: "Entre a un edificio. Cierre y asegure puertas y ventanas. Prepárese para valerse por sí mismo hasta nuevo aviso o hasta que el personal de emergencia le dé más instrucciones." },
  ],
  go: [
    "Salga temprano. Si se siente en peligro, no espere a que se lo digan. En un incendio rápido puede no haber tiempo para avisar a todos.",
    "Siga de inmediato las instrucciones de las autoridades.",
    "Vaya a un lugar que eligió con anticipación, fuera de la zona del incendio: un centro de evacuación, un refugio o un motel.",
    "Tome una ruta que se aleje del fuego y tenga otra de respaldo por si las calles están bloqueadas.",
    "Use mangas largas, pantalones largos, zapatos gruesos, gorra, gafas protectoras y un pañuelo seco. El algodón es lo mejor.",
    "Lleve a sus mascotas. Asegúrese de que su kit esté en el carro.",
    "Diga a su familia y amigos a dónde va.",
  ],
  trapped: [
    {
      title: "En casa",
      items: [
        "Llame al 911 y dé su ubicación.",
        "Cierre el medidor de gas. Llene los lavabos y las tinas de agua.",
        "Mantenga puertas y ventanas cerradas, pero sin llave. Quite las cortinas.",
        "Encienda las luces de adentro y de afuera.",
        "Quédese adentro, lejos de las paredes exteriores.",
      ],
    },
    {
      title: "En un carro",
      items: [
        "Estaciónese lejos de la vegetación.",
        "Cierre todas las ventanas y respiraderos.",
        "Cúbrase con una cobija o chaqueta de lana o de algodón.",
        "Acuéstese en el piso del carro.",
        "Llame al 911 y dé su ubicación.",
      ],
    },
    {
      title: "A pie",
      items: [
        "Vaya a un área sin vegetación, o a una zanja o un lugar bajo en terreno plano.",
        "Acuéstese boca abajo y cúbrase el cuerpo.",
        "Llame al 911 y dé su ubicación.",
      ],
    },
  ],
  returning: [
    "No regrese hasta que las autoridades digan que es seguro.",
    "Tenga cuidado con los cables eléctricos caídos.",
    "Revise los tanques, reguladores y líneas de propano antes de abrir el gas.",
    "Revise la casa con cuidado en busca de brasas escondidas.",
  ],
  photoAlts: {
    cover: "Humo del incendio Eaton elevándose sobre las crestas de las montañas San Gabriel.",
    ready: "Bomberos cortando y despejando maleza seca en una ladera debajo de una casa.",
    set: "Una bolsa de suministros de emergencia con botellas de agua, una linterna, baterías, guantes, gafas protectoras, un silbato y un poncho.",
    go: "Camiones de bomberos en una calle residencial de noche mientras arde una casa.",
  },
};
